#server:
#  port: 8080

---
#server:
#  port: 8085
#spring:
#  profiles: dev

---
#server:
#  port: 8082
#spring:
#  profiles: prod

---
#person:
#  last-name: 廷云
#  age: 24
#  birth: 1995/08/30
#  boss: false
#  maps: {k1: v1, k2: v2}
#  lists: [1, 2, 3]
#  dog:
#    name: 小狗
#    age: 2
